# Bayesian model
BAYESIAN_PRIOR_MEAN = 1.0
BAYESIAN_PRIOR_VARIANCE = 0.1
MIN_SESSIONS_PER_BUCKET = 3

# CUSUM
CUSUM_SLACK_FACTOR = 0.5
CUSUM_THRESHOLD_FACTOR = 4.5

# Kalman Filter
KALMAN_LEVEL_NOISE = 0.01
KALMAN_SLOPE_NOISE = 0.0001

# Gaussian Process
GP_LENGTH_SCALE = 7.0
GP_NOISE_RATIO = 0.20
GP_EXTRAPOLATION_CI_INFLATION = 1.5
GP_EXTRAPOLATION_DAYS = 14

# Streak
STREAK_LEVEL_THRESHOLDS = (0, 0.01, 0.50, 1.00)
